/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package client;

import data.Message;

import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.*;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Calendar;

/**
 *
 * @author nkhieu
 */
public class ChatPanel extends javax.swing.JPanel {
    private String name;
    private ClientCore clientCore;
    private Box vertical = Box.createVerticalBox();
    /**
     * Creates new form ChatPanelGUi
     */
    public ChatPanel(String name, ClientCore clientCore) {
        this.clientCore = clientCore;
        this.name = name;
        initComponents();
    }
    public String getName(){
        return name;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        chatPnl = new javax.swing.JPanel();
        msgPanel = new javax.swing.JPanel();
        fileBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        msgBtn = new javax.swing.JButton();

        chatPnl.setLayout(new java.awt.BorderLayout());
        jScrollPane3.setViewportView(chatPnl);

        fileBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        fileBtn.setText("File");
        fileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileBtnActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        msgBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        msgBtn.setText("Send");
        msgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    msgBtnActionPerformed(evt);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        });
        javax.swing.GroupLayout msgPanelLayout = new javax.swing.GroupLayout(msgPanel);
        msgPanel.setLayout(msgPanelLayout);
        msgPanelLayout.setHorizontalGroup(
                msgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(msgPanelLayout.createSequentialGroup()
                                .addComponent(fileBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(msgBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(12, 12, 12))
        );
        msgPanelLayout.setVerticalGroup(
                msgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, msgPanelLayout.createSequentialGroup()
                                .addContainerGap(14, Short.MAX_VALUE)
                                .addGroup(msgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(msgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fileBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(msgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 856, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(566, 566, 566)
                                .addComponent(msgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 11, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 59, Short.MAX_VALUE)))
        );
    }// </editor-fold>


    private void fileBtnActionPerformed(java.awt.event.ActionEvent evt) {
        String msg = jTextArea1.getText();
        System.out.println(msg);
    }
    private void msgBtnActionPerformed(java.awt.event.ActionEvent evt) throws IOException {
        String msg = jTextArea1.getText();
        if(msg.equals("")){
            return;
        }
        JPanel p2 = formatLabel(msg, "");
        chatPnl.setLayout(new BorderLayout());
        JPanel right = new JPanel(new BorderLayout());
        right.add(p2, BorderLayout.LINE_END);
        vertical.add(right);
        vertical.add(Box.createVerticalStrut(15));
        chatPnl.add(vertical, BorderLayout.PAGE_START);
        Message newMsg = new Message();
        if(this.name.equals("ALL")){
            newMsg.setReceiverType(Message.ReceiverType.GROUP);
            newMsg.setSender(clientCore.getClientName());
        }else{
            newMsg.setReceiver(this.name);
            newMsg.setReceiverType(Message.ReceiverType.PERSON);
            newMsg.setSender(clientCore.getClientName());
        }
        newMsg.setContent(msg);
        newMsg.setMessageType(Message.MessageType.MSG);
        clientCore.sendMessage(newMsg);
        jTextArea1.setText("");
        validate();
    }
    private JPanel formatLabel(String msg, String sender){
        JPanel p3 = new JPanel();
        p3.setLayout(new BoxLayout(p3, BoxLayout.Y_AXIS));
        JLabel l1 = new JLabel("<html><p style = \"width : 150px\">"+msg+"</p></html>");
        l1.setFont(new Font("Tahoma", Font.PLAIN, 16));
        l1.setBackground(new JList<>().getSelectionBackground());
        l1.setForeground(new JList<>().getSelectionForeground());
        l1.setOpaque(true);
        l1.setBorder(new EmptyBorder(15,15,15,50));
        JLabel l2 = new JLabel();
        Calendar cal = Calendar.getInstance();
        SimpleDateFormat sdf = new SimpleDateFormat("HH:mm");
        if(sender ==""){
            l2.setText(sdf.format(cal.getTime()));
        }else{
            l2.setText(sender+" ("+sdf.format(cal.getTime())+")");
        }
        p3.add(l2);
        p3.add(l1);
        return p3;
    }
    public void appendNewMsg(String msg, String sender){
        JPanel p2 = formatLabel(msg, sender);
        JPanel left = new JPanel(new BorderLayout());
        left.add(p2, BorderLayout.LINE_START);
        vertical.add(left);
        vertical.add(Box.createVerticalStrut(15));
        chatPnl.add(vertical, BorderLayout.PAGE_START);
        validate();
    }

    // Variables declaration - do not modify
    private javax.swing.JPanel chatPnl;
    private javax.swing.JButton fileBtn;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton msgBtn;
    private javax.swing.JPanel msgPanel;
    // End of variables declaration
}
